name: FTC Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write        # для gh-pages
  id-token: write     # OIDC – deploy-pages

jobs:
  build_and_analyze:
    name: Build APK  +  Static Analysis  +  Upload reports
    runs-on: ubuntu-latest

    steps:
      # ───── Source code ──────────────────────────────────────────────────────────
      - name: Checkout
        uses: actions/checkout@v4

      # ───── Toolchain ───────────────────────────────────────────────────────────
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licences
        run: yes | sdkmanager --licenses

      # ───── Build & Static analysis ─────────────────────────────────────────────
      - name: Run SpotBugs
        run: ./gradlew :TeamCode:spotbugsDebug || true

      - name: Run Checkstyle
        run: ./gradlew :TeamCode:checkstyleDebug || true

      - name: Run Lint
        run: ./gradlew :FtcRobotController:lintDebug || true

      - name: Assemble Debug APK
        run: ./gradlew :FtcRobotController:assembleDebug

      - name: Collect HTML reports
        if: always()
        run: |
          REPORTS=pages
          mkdir -p $REPORTS
          mkdir -p $REPORTS/TeamCode $REPORTS/FtcRobotController
          

          if [ -d TeamCode/build/reports ]; then
            cp -r TeamCode/build/reports $REPORTS/TeamCode
          fi
          if [ -d FtcRobotController/build/reports ]; then
            cp -r FtcRobotController/build/reports $REPORTS/FtcRobotController
          fi
          
          cat > $REPORTS/index.html <<'EOF'
          <!doctype html><html lang="en"><meta charset="utf-8">
          <h1>FTC Android CI Reports</h1>
          <ul>
            <li><a href="FtcRobotController/lint-results-debug.html">Lint (app)</a></li>
            <li><a href="TeamCode/checkstyle/debug.html">Checkstyle (TeamCode)</a></li>
            <li><a href="TeamCode/spotbugs/debug.html">SpotBugs (TeamCode)</a></li>
          </ul>
          EOF
          touch $REPORTS/.nojekyll


      - name: Upload Pages artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      # ───── APK artefact ────────────────────────────────────────────────────────
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: FtcRobotController-debug-apks
          path: FtcRobotController/build/outputs/apk/debug/*.apk

  # ───── Publish reports to GitHub Pages ─────────────────────────────────────────
  deploy_pages:
    name: Deploy to GitHub Pages
    needs: build_and_analyze
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
